-- migrations/create_posts.sql
-- Create posts table for ScrapLink
-- migrations/create_posts.sql
-- Create posts table for ScrapLink and example Row-Level Security (RLS) policies.
-- IMPORTANT: Review these policies before applying in production.

-- This migration creates a posts table that stores an uploader_id (uuid) which is
-- compared against the authenticated user's id (auth.uid()) in policies.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  image_url text,
  description text,
  type text,
  location text,
  amount numeric,
  uploader text,
  uploader_id uuid,
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table public.posts enable row level security;

-- Policy: allow anyone to SELECT posts (public read). If you prefer restricted reads,
-- change the policy to limit fields or require authenticated users.
create policy "public_select" on public.posts
  for select
  using (true);

-- Policy: allow INSERT only when the uploader_id matches the authenticated user.
-- This prevents clients from inserting posts that claim to be from a different user.
create policy "insert_authenticated" on public.posts
  for insert
  with check (auth.uid() IS NOT NULL AND uploader_id = auth.uid());

-- Policy: allow UPDATE only for the owner (uploader_id == auth.uid())
create policy "owner_update" on public.posts
  for update
  using (uploader_id = auth.uid())
  with check (uploader_id = auth.uid());

-- Policy: allow DELETE only for the owner
create policy "owner_delete" on public.posts
  for delete
  using (uploader_id = auth.uid());

-- Notes:
-- 1) The client must set uploader_id to the logged-in user's id when inserting.
--    For example, in the browser you can get the user id via auth.getUser() and include
--    it in the insert payload. Alternatively, create a Postgres trigger to set uploader_id
--    from auth if you use Supabase Edge functions.
-- 2) If you want public inserts (not recommended), adjust the insert policy accordingly.
-- 3) Run this SQL in the Supabase SQL editor, and ensure your anon/public key has
--    appropriate permissions (or use service role for server-side operations).

